[profile.default]
  solc_version = "0.8.19"
  verbosity = 3

[profile.no_optimizer_no_metadata]
  bytecode_hash = "none"
  optimizer = false
  out = "out_no_optimizer_no_metadata"

[profile.yes_optimizer_no_metadata]
  bytecode_hash = "none"
  optimizer = true
  out = "out_yes_optimizer_no_metadata"

[profile.no_via_ir_no_metadata]
  bytecode_hash = "none"
  via_ir = false
  out = "out_no_via_ir_no_metadata"

[profile.yes_via_ir_no_metadata]
  bytecode_hash = "none"
  via_ir = true
  out = "out_yes_via_ir_no_metadata"

[profile.no_metadata_no_cbor]
  bytecode_hash = "none"
  cbor_metadata = false
  out = "out_no_metadata_no_cbor"

[profile.no_metadata_yes_cbor]
  bytecode_hash = "none"
  out = "out_no_metadata_yes_cbor"

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true
